# Generated by Django 4.0 on 2022-01-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='personality',
            new_name='number_of_lines',
        ),
        migrations.RenameField(
            model_name='line',
            old_name='emotion',
            new_name='sentiment',
        ),
        migrations.AddField(
            model_name='character',
            name='sentiment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
