# Generated by Django 4.0 on 2022-01-03 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_personality_character_number_of_lines_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line',
        ),
    ]
