# Generated by Django 4.0 on 2022-01-31 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='sentiment',
            new_name='data',
        ),
    ]
